#' Insert labels in raw SINASC data
#'
#' The function download.sinasc create a data frame about the SINASC data with no treatment. This function is usual to realize the
#' treatment of the data and replace the codes by respective labels.
#'
#' @param x Raw SINASC data generated by the function download.sinasc with all columns.
#' @seealso \code{\link{download.sinasc}}
#' @author Luan Augusto, \email{luanguto87@gmail.com}
#' @return A data frame from SINASC with all codes replaced by their respective labels.
#' @export
#'
#' @examples
label.sinasc <- function(x){
  require(foreign)
  require(dplyr)
  require(lubridate)
  base <- x


  base <- base %>%
    mutate(ESTCIVMAE=recode(ESTCIVMAE,`1`="Solteira",`2`="Casada",`3`="Viúva",`4`="Divorciada",`5`="União Estável",`9`="Ignorado"),

           LOCNASC=recode(LOCNASC,`1`="Hospital",`2`="Outros estabelecimentos de saúde",`3`="Domicílio",`4`="Outros",`5`="Aldeia Indígena",`9`="Ignorado"),

           ESCMAE=recode(ESCMAE,`1`="Nenhuma",`2`="1 a 2 anos",`3`="4 a 7 anos",`4`="8 a 11 anos",`5`="12 e mais",`9`="Ignorado",`0`="Ignorado"),

           ESCMAE2010=recode(ESCMAE2010,`0`="Sem escolaridade",`1`="Fundamental I (1ª a 4ª série)",
                             `2`="Fundamental II (5ª a 8º série)",`3`="Médio (antigo 2ª Grau)",
                             `4`="Superior incompleto",`5`="Superior completo",`9`="Ignorado"),

           RACACOR=recode(RACACOR,`1`="Branca",`2`="Preta",`3`="Amarela",`4`="Parda",`5`="Indígena",`9`="Ignorado"),

           IDANOMAL=recode(IDANOMAL,`1`="Sim",`2`="Não",`9`="Ignorado"),

           SEXO=recode(SEXO,`1`="Masculino",`2`="Feminino","M"="Masculino","F"="Feminino",`0`="Ignorado","I"="Ignorado",`9`="Ignorado"),

           GESTACAO=recode(GESTACAO,`1`="Menos de 22 semanas",`2`="22 a 27 semanas",`3`="28 a 31 semanas",`4`="32 a 36 semanas",
                           `5`="37 a 41 semanas",`6`="42 semanas e mais",`9`="Ignorado"),

           GRAVIDEZ=recode(GRAVIDEZ,`1`="Única",`2`="Dupla",`3`="Tripla ou mais",`9`="Ignorado"),

           PARTO=recode(PARTO,`1`="Vaginal",`2`="Cesário",`9`="Ignorado"),

           RACACORMAE=recode(RACACORMAE,`1`="Branca",`2`="Preta",`3`="Amarela",`4`="Parda",`5`="Indígena",`9`="Ignorado"),

           TPMETESTIM=recode(TPMETESTIM,`1`="Exame físico",`2`="Outro método",`9`="Ignorado"),

           CONSULTAS=recode(CONSULTAS,`1`="Nenhuma",`2`="de 1 a 3",`3`="de 4 a 6",`4`="7 e mais",`9`="Ignorado"),

           MESPRENAT=recode(MESPRENAT,`01`="Primeiro",`02`="Segundo",`03`="Terceiro",`04`="Quarto",`05`="Quinto",`06`="Sexto",`07`="Sétimo",
                            `08`="Oitavo",`09`="Nono",`99`="Ignorado"),

           CONSULTAS=recode(CONSULTAS,`1`="Nenhuma",`2`="de 1 a 3;",`3`="de 4 a 6",`4`="7 e mais",`9`="Ignorado"),

           TPAPRESENT=recode(TPAPRESENT,`1`="Cefálica",`2`="Pélvica ou podálica",`3`="Transversa",`9`="Ignorado"),

           STTRABPART=recode(STTRABPART,`1`="Sim",`2`="Não",`9`="Ignorado"),

           STCESPARTO=recode(STCESPARTO,`1`="Sim",`2`="Não",`3`="Não se aplica",`9`="Ignorado"),

           TPNASCASSI=recode(TPNASCASSI,`1`="Médico",`2`="Enfermeira/Obstetriz",`3`="Parteira",`4`="Outro",`9`="Ignorado"),

           TPFUNCRESP=recode(TPFUNCRESP,`1`="Médico",`2`="Enfermagem",`3`="Parteira",`4`="Func. Cartório",`5`="Outros",`9`="Ignorado"),

           TPDOCRESP=recode(TPDOCRESP,`1`="CNES",`2`="CRM",`3`="COREN",`4`="RG",`5`="CPF",`9`="Ignorado"),

           ESCMAEAGR1=recode(ESCMAEAGR1,`00`="Sem Escolaridade",`01`="Fundamental I Incompleto",`02`="Fundamental I Completo",
                             `03`="Fundamental II Incompleto",`04`="Fundamental II Completo",`05`="Ensino Médio Incompleto",
                             `06`="Ensino Médio Completo",`07`="Superior Incompleto",`08`="Superior Completo",`09`="Ignorado",
                             `10`="Fundamental I Incompleto ou Inespecífico",`11`="Fundamental II Incompleto ou Inespecífico",
                             `12`="Ensino Médio Incompleto ou Inespecífico"),

           STDNEPIDEM=recode(STDNEPIDEM,`1`="Sim",`0`="Não",`9`="Ignorado"),

           STDNNOVA=recode(STDNNOVA,`1`="Sim",`0`="Não",`9`="Ignorado"),

           APGAR1=recode(APGAR1,`99`="Ignorado"),

           APGAR5=recode(APGAR5,`99`="Ignorado"),

           TPROBSON=recode(TPROBSON,`01`="Nulípara, gest un, cefál >37sem, tp espontaneo",`02`="Nulípara, gest un, cefál >37sem c/ind CS préTP",
                             `03`="Multípara,(s/ces prev)gest un cef >37sem espon",`04`=" Multíp,(s/ces prev)gest un cef >37s ind/CSpréTP",`05`="C/CS ant gestação única, cefálica, > 37 semanas",
                             `06`="Todos partos pélvicos em nulíparas",`07`="Todos partos pélv em multíparas (incl CS prévia)",`08`="Todas gest múltiplas (incluindo CS prévia)",`09`="Todas apres anormais (incluindo CS prévia)",
                             `10`="Todas gest unic cefal <36sem (incl CS prévia)",`11`="Nasc n clas por aus resp aos itens necessarios"),

           PARIDADE=recode(PARIDADE,`0`="nulípara",`1`="multipara",`9`="Ignorado"),

           KOTELCHUCK=recode(KOTELCHUCK,`1`="Não fez pré-natal",`2`="Inadequado",`3`="Intermediário",`4`="Adequado",
                             `5`="Mais que adequado",`6`="Não Classificados",`9`="Ignorado"),

           ORIGEM=recode(ORIGEM,`1`="Oracle",`2`="FTP",`3`="SEAD"))

  base <- base %>%
    left_join(CID10%>% select(CID10, DESCR),by=join_by(CODANOMAL==CID10),keep = FALSE)

  base <- base %>%
    left_join(
      left_join(CADMUN%>% select(MUNCOD,MUNNOMEX,UFCOD),TABUF%>% select(SIGLA_UF,CODIGO),by=join_by(UFCOD==CODIGO),keep = F),
      by=join_by(CODMUNRES==MUNCOD),keep = F
    )
  base <- base %>%
    rename(MUNRES=MUNNOMEX)

  base <- base %>%
    left_join(CADMUN%>% select(MUNCOD,MUNNOMEX),by=join_by(CODMUNNASC==MUNCOD),keep = FALSE)

  base$CODOCUPMAE <- gsub("^0+","",base$CODOCUPMAE)

  base$CODOCUPMAE <- as.integer(base$CODOCUPMAE)

  base <- base %>%
    left_join(ocup,by=join_by(CODOCUPMAE==CODIGO),keep = F)


  base$TITULO <- ifelse(base$CODOCUPMAE=="999991","Estudante",
                        ifelse(base$CODOCUPMAE=="999992","Dona de Casa",
                               ifelse(base$CODOCUPMAE=="999993","Aposentada/Pensionista",
                                      ifelse(base$CODOCUPMAE=="999994","Desempregada",
                                             ifelse(base$CODOCUPMAE=="516115","Esteticista",
                                                    ifelse(base$CODOCUPMAE=="516135","Massagista",
                                                           ifelse(base$CODOCUPMAE=="514210","Faxineiro",
                                                                  ifelse(base$CODOCUPMAE=="422215","Recepcionista de seguro saúde",
                                                                         ifelse(base$CODOCUPMAE=="354110","Agenciador de propaganda",
                                                                                ifelse(base$CODOCUPMAE=="517315","Agente de segurança penitenciária",
                                                                                       ifelse(base$CODOCUPMAE=="510125","Chefe de cozinha",base$TITULO)))))))))))
  base <- base %>%
    rename(OCUPMAE = TITULO, UF = SIGLA_UF, MUNNASC = MUNNOMEX, ANOMALIA = DESCR,ESTABELECIMENTO = FANTASIA)

  base <- base %>%
    mutate(FAIXA_PESO = case_when(
      PESO>=4000 ~ "4000g e mais",
      PESO>=3000 & PESO<4000 ~ "3000g a 3999g",
      PESO>=2500 & PESO<3000 ~ "2500g a 2999g",
      PESO>=1500 & PESO<2500 ~ "1500g a 2499g",
      PESO>=1000 & PESO<1500 ~ "1000g a 1499g",
      PESO<1000 ~ "0g a 999g"
    ))

  base <- base %>%
    mutate(FAIXA_ETARIA_MAE = case_when(
      IDADEMAE>=51 ~ "51 anos ou mais",
      IDADEMAE>=41 & IDADEMAE<51 ~ "41 a 50 anos",
      IDADEMAE>=31 & IDADEMAE<41 ~ "31 a 40 anos",
      IDADEMAE>=21 & IDADEMAE<31 ~ "21 a 30 anos",
      IDADEMAE>=15 & IDADEMAE<21 ~ "15 a 20 anos",
      IDADEMAE<15 ~ "menos de 15 anos"
    ))

  base <- base %>%
    mutate(COD_FAIXA_ETARIA=case_when(
      IDADEMAE>=51 ~ 6,
      IDADEMAE>=41 & IDADEMAE<51 ~ 5,
      IDADEMAE>=31 & IDADEMAE<41 ~ 4,
      IDADEMAE>=21 & IDADEMAE<31 ~ 3,
      IDADEMAE>=15 & IDADEMAE<21 ~ 2,
      IDADEMAE<15 ~ 1
    ))

  base <- base %>%
    mutate(COD_FAIXA_PESO = case_when(
      PESO>=4000 ~ 6,
      PESO>=3000 & PESO<4000 ~ 5,
      PESO>=2500 & PESO<3000 ~ 4,
      PESO>=1500 & PESO<2500 ~ 3,
      PESO>=1000 & PESO<1500 ~ 2,
      PESO<1000 ~ 1
    ))

  base <- base %>%
    mutate(COD_GESTACAO = case_when(
      GESTACAO=="Ignorado" ~ 7,
      GESTACAO=="42 semanas e mais" ~ 6,
      GESTACAO=="37 a 41 semanas" ~ 5,
      GESTACAO=="32 a 36 semanas" ~ 4,
      GESTACAO=="28 a 31 semanas" ~ 3,
      GESTACAO=="22 a 27 semanas" ~ 2,
      GESTACAO=="Menos de 22 semanas" ~ 1
    ))

  base <- base %>%
    mutate(COD_CONSULTAS = case_when(
      CONSULTAS=="Ignorado" ~ 5,
      CONSULTAS=="7 e mais" ~ 4,
      CONSULTAS=="de 4 a 6" ~ 3,
      CONSULTAS=="de 1 a 3" ~ 2,
      CONSULTAS=="Nenhuma" ~ 1
    ))

  base <- base %>%
    mutate(COD_ESCOLARIDADE = case_when(
      ESCMAE=="Ignorado" ~ 6,
      ESCMAE=="12 e mais" ~ 5,
      ESCMAE=="8 a 11 anos" ~ 4,
      ESCMAE=="4 a 7 anos" ~ 3,
      ESCMAE=="1 a 2 anos" ~ 2,
      ESCMAE=="Nenhuma" ~ 1
    ))

  base <- base %>%
    mutate(COD_GRAVIDEZ = case_when(
      GRAVIDEZ=="Ignorado" ~ 4,
      GRAVIDEZ=="Tripla e mais" ~ 3,
      GRAVIDEZ=="Dupla" ~ 2,
      GRAVIDEZ=="Única" ~ 1
    ))

  base <- base %>%
    mutate(FAIXA_APGAR5 = case_when(
      APGAR5 %in% c("00","01","02","03") ~ "0 a 3",
      APGAR5 %in% c("04","05","06","07") ~ "4 a 7",
      APGAR5 %in% c("08","09","10") ~ "8 a 10",
      APGAR5 == "Ignorado" ~ "Ignorado"
    ))

  base <- base %>%
    mutate(
      ANO=year(DTNASC),MES_ANO=paste0(year(DTNASC),"-",month(DTNASC),"-","01")
    )

  base <- base %>%
    mutate(
      ANO=as.character(ANO),MES_ANO=as.Date(MES_ANO))

  base <- data.frame(lapply(base, function(x) if (is.factor(x)) as.character(x) else x))
  return(base)
}

