panel.sinasc <- function(x){
  require(dplyr)
  base <- x %>%
    select(CODESTAB,ESTABELECIMENTO,`LOCAL DE NASCIMENTO`=LOCNASC,CODMUNNASC,UF,`MUNICÍPIO DE NASCIMENTO`=MUNNASC,SEXO,PESO,`FAIXA DE PESO`=FAIXA_PESO,`SEMANAS GESTAÇÃO`=SEMAGESTAC,`GESTAÇÃO`=GESTACAO,GRAVIDEZ,PARTO,DTNASC,HORANASC,ANO,`MES-ANO`=MES_ANO,`RAÇA/COR`=RACACOR,`CONSULTAS PRÉ-NATAL`=CONSULTAS, APGAR1, APGAR5,
           `IDADE DA MÃE`= IDADEMAE,`FAIXA ETÁRIA DA MÃE`=FAIXA_ETARIA_MAE,`ESTADO CIVIL DA MÃE` = ESTCIVMAE,`RAÇA/COR DA MÃE`=RACACORMAE, `ESCOLARIDADE DA MÃE` = ESCMAE2010, `ANOS DE ESCOLARIDADE DA MÃE` = ESCMAE, CODMUNRES,`MUNICÍPIO RESIDENCIA MÃE`= MUNRES,`OCUPAÇÃO DA MÃE`=OCUPMAE,
           `ANOMALIA CONGÊNITA`=IDANOMAL,COD_FAIXA_ETARIA,COD_FAIXA_PESO,COD_GESTACAO,COD_CONSULTAS,COD_ESCOLARIDADE,COD_GRAVIDEZ)

  colnames(base) <- iconv(colnames(base), to = "UTF-8")

  base[-30] <- lapply(base[-30], function(col) {
    if (is.character(col)) iconv(col, to = "UTF-8") else col
  })

  return(base)
}

